// Importing necessary modules and components
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Importing global styles
import Navbar from "./components/Navbar"; // Importing Navbar component
import Providers from "./redux/Provider"; // Importing Providers component

// Creating an instance of the Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata object containing information about the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component serving as the layout for the entire application
export default function RootLayout({
  children, // Children components passed to the layout
}: Readonly<{
  children: React.ReactNode; // Defining children prop
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Applying Inter font class to body */}
        <Providers> {/* Wrapping components with Providers for Redux */}
          <Navbar /> {/* Rendering Navbar component */}
          {children} {/* Rendering children components */}
        </Providers>
      </body>
    </html>
  );
}
